language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - TRANSPORT=jackrabbit PACKAGE_VERSION=high
  - TRANSPORT=doctrine_dbal PACKAGE_VERSION=high

matrix:
  include:
    - php: 5.3.3
      env: TRANSPORT=doctrine_dbal COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.3.3
      env: TRANSPORT=jackrabbit COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: TRANSPORT=doctrine_dbal SYMFONY="3"

before_script:
  - composer self-update
  - if [[ "$SYMFONY" == "3" ]]; then composer require symfony/symfony "3.*@dev" --no-update; fi
  - ./tests/travis_${TRANSPORT}.sh

script: phpunit -c tests/phpunit_${TRANSPORT}.xml.dist

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
